from src.lib.pipeline.transforms.highest_ps_ranking import build_highest_ps_outputs


def test_build_highest_ps_outputs_returns_sector_relative_usa_ranking_and_benchmark():
    rows = [
        {
            "section_key": "usa",
            "section_label": "USA High P/S Leaders",
            "universe_key": "sp500",
            "universe_label": "S&P 500",
            "as_of_date": "2026-06-15",
            "ticker": "NVDA",
            "company": "NVIDIA",
            "country_code": "US",
            "country_name": "United States",
            "sector": "Information Technology",
            "market_cap": 3100.0,
            "average_daily_traded_value": 52000.0,
            "ps_ratio": 24.10,
            "index_weight_pct": 6.10,
        },
        {
            "section_key": "usa",
            "section_label": "USA High P/S Leaders",
            "universe_key": "sp500",
            "universe_label": "S&P 500",
            "as_of_date": "2026-06-15",
            "ticker": "MSFT",
            "company": "Microsoft",
            "country_code": "US",
            "country_name": "United States",
            "sector": "Information Technology",
            "market_cap": 3200.0,
            "average_daily_traded_value": 21000.0,
            "ps_ratio": 12.00,
            "index_weight_pct": 6.50,
        },
        {
            "section_key": "usa",
            "section_label": "USA High P/S Leaders",
            "universe_key": "sp500",
            "universe_label": "S&P 500",
            "as_of_date": "2026-06-15",
            "ticker": "V",
            "company": "Visa",
            "country_code": "US",
            "country_name": "United States",
            "sector": "Financials",
            "market_cap": 540.0,
            "average_daily_traded_value": 9000.0,
            "ps_ratio": 16.00,
            "index_weight_pct": 1.10,
        },
        {
            "section_key": "usa",
            "section_label": "USA High P/S Leaders",
            "universe_key": "sp500",
            "universe_label": "S&P 500",
            "as_of_date": "2026-06-15",
            "ticker": "MA",
            "company": "Mastercard",
            "country_code": "US",
            "country_name": "United States",
            "sector": "Financials",
            "market_cap": 430.0,
            "average_daily_traded_value": 8000.0,
            "ps_ratio": 11.00,
            "index_weight_pct": 0.90,
        },
        {
            "section_key": "usa",
            "section_label": "USA High P/S Leaders",
            "universe_key": "sp500",
            "universe_label": "S&P 500",
            "as_of_date": "2026-06-15",
            "ticker": "AAPL",
            "company": "Apple",
            "country_code": "US",
            "country_name": "United States",
            "sector": "Information Technology",
            "market_cap": 2900.0,
            "average_daily_traded_value": 18000.0,
            "ps_ratio": 8.00,
            "index_weight_pct": 6.00,
        },
        {
            "section_key": "usa",
            "section_label": "USA High P/S Leaders",
            "universe_key": "sp500",
            "universe_label": "S&P 500",
            "as_of_date": "2026-06-15",
            "ticker": "SMALL",
            "company": "Small Co",
            "country_code": "US",
            "country_name": "United States",
            "sector": "Information Technology",
            "market_cap": 12.0,
            "average_daily_traded_value": 40.0,
            "ps_ratio": 40.00,
            "index_weight_pct": 0.01,
        },
        {
            "section_key": "usa",
            "section_label": "USA High P/S Leaders",
            "universe_key": "sp500",
            "universe_label": "S&P 500",
            "as_of_date": "2026-06-15",
            "ticker": "BROKEN",
            "company": "Broken Co",
            "country_code": "US",
            "country_name": "United States",
            "sector": "Information Technology",
            "market_cap": 100.0,
            "average_daily_traded_value": 100.0,
            "ps_ratio": 0.0,
            "index_weight_pct": 0.02,
        },
    ]

    outputs = build_highest_ps_outputs(rows, ranking_size=25, eligibility_fraction=0.66)

    assert outputs["as_of"] == "2026-06-15"
    assert outputs["references"] == []
    assert outputs["sections"] == [
        {
            "key": "usa",
            "label": "USA High P/S Leaders",
            "universe_key": "sp500",
            "universe_label": "S&P 500",
            "as_of_date": "2026-06-15",
            "unavailable": False,
                    "benchmark": {
                        "key": "sp500",
                        "label": "S&P 500 Average P/S",
                    "average_ps_ratio": 14.75,
                    "top_basket_average_ps_ratio": 14.75,
                    "top_basket_index_weight_pct": 19.7,
                    "eligible_constituent_count": 4,
                },
                "ranking": [
                {
                    "rank": 1,
                    "ticker": "NVDA",
                    "company": "NVIDIA",
                    "country_code": "US",
                        "country_name": "United States",
                        "sector": "Information Technology",
                        "ps_ratio": 24.1,
                        "sector_average_ps_ratio": 14.7,
                        "relative_to_sector_multiple": 1.64,
                        "index_weight_pct": 6.1,
                    },
                    {
                    "rank": 2,
                    "ticker": "V",
                    "company": "Visa",
                    "country_code": "US",
                        "country_name": "United States",
                        "sector": "Financials",
                        "ps_ratio": 16.0,
                        "sector_average_ps_ratio": 16.0,
                        "relative_to_sector_multiple": 1.0,
                        "index_weight_pct": 1.1,
                    },
                    {
                        "rank": 3,
                        "ticker": "MSFT",
                        "company": "Microsoft",
                        "country_code": "US",
                        "country_name": "United States",
                        "sector": "Information Technology",
                        "ps_ratio": 12.0,
                        "sector_average_ps_ratio": 14.7,
                        "relative_to_sector_multiple": 0.82,
                        "index_weight_pct": 6.5,
                    },
                    {
                        "rank": 4,
                        "ticker": "AAPL",
                        "company": "Apple",
                        "country_code": "US",
                        "country_name": "United States",
                        "sector": "Information Technology",
                        "ps_ratio": 8.0,
                        "sector_average_ps_ratio": 14.7,
                        "relative_to_sector_multiple": 0.54,
                        "index_weight_pct": 6.0,
                    },
                ],
            }
        ]


def test_build_highest_ps_outputs_marks_section_unavailable_when_no_rows_survive():
    outputs = build_highest_ps_outputs([], ranking_size=25, eligibility_fraction=0.66)

    assert outputs == {
        "as_of": None,
        "references": [],
        "sections": [],
    }
