from src.lib.pipeline.transforms.currency_irp import build_currency_irp_outputs


def test_build_currency_irp_outputs_creates_tenor_rows_and_irp_availability():
    staging_rows = [
        {
            "series_id": "eurusd_spot_daily",
            "observation_date": "2026-05-30",
            "numeric_value": 1.14,
            "category": "fx_spot",
            "region": "FX",
            "frequency": "daily",
            "unit": "usd_per_eur",
            "provider": "ecb",
            "source_url": "https://data.ecb.europa.eu/data/datasets/EXR/EXR.D.USD.EUR.SP00.A",
            "is_valid": True,
        },
        {
            "series_id": "eur_3m_rate",
            "observation_date": "2026-05-30",
            "numeric_value": 2.0,
            "category": "market_rate",
            "region": "EU",
            "frequency": "daily",
            "unit": "percent",
            "provider": "ecb",
            "source_url": "https://data.ecb.europa.eu/data/datasets/EST/EST.B.EU000A2QQF32.CR",
            "is_valid": True,
        },
        {
            "series_id": "eur_6m_rate",
            "observation_date": "2026-05-30",
            "numeric_value": 2.1,
            "category": "market_rate",
            "region": "EU",
            "frequency": "daily",
            "unit": "percent",
            "provider": "ecb",
            "source_url": "https://data.ecb.europa.eu/data/datasets/EST/EST.B.EU000A2QQF40.CR",
            "is_valid": True,
        },
        {
            "series_id": "eur_12m_rate",
            "observation_date": "2026-05-30",
            "numeric_value": 2.2,
            "category": "market_rate",
            "region": "EU",
            "frequency": "daily",
            "unit": "percent",
            "provider": "ecb",
            "source_url": "https://data.ecb.europa.eu/data/datasets/EST/EST.B.EU000A2QQF57.CR",
            "is_valid": True,
        },
        {
            "series_id": "usd_3m_rate",
            "observation_date": "2026-05-30",
            "numeric_value": 4.0,
            "category": "market_rate",
            "region": "US",
            "frequency": "daily",
            "unit": "percent",
            "provider": "fred",
            "source_url": "https://fred.stlouisfed.org/series/DTB3",
            "is_valid": True,
        },
        {
            "series_id": "usd_6m_rate",
            "observation_date": "2026-05-30",
            "numeric_value": 4.1,
            "category": "market_rate",
            "region": "US",
            "frequency": "daily",
            "unit": "percent",
            "provider": "fred",
            "source_url": "https://fred.stlouisfed.org/series/DTB6",
            "is_valid": True,
        },
        {
            "series_id": "usd_12m_rate",
            "observation_date": "2026-05-30",
            "numeric_value": 4.2,
            "category": "market_rate",
            "region": "US",
            "frequency": "daily",
            "unit": "percent",
            "provider": "fred",
            "source_url": "https://fred.stlouisfed.org/series/DTB1YR",
            "is_valid": True,
        },
    ]

    outputs = build_currency_irp_outputs(staging_rows)

    assert outputs["snapshot_rows"] == [
        {
            "pair_key": "eurusd",
            "as_of_date": "2026-05-30",
            "tenor": "3M",
            "spot": 1.14,
            "eur_rate": 2.0,
            "usd_rate": 4.0,
            "rate_spread": -2.0,
            "cip_implied_forward": 1.1344,
            "uip_implied_move_pct": -0.5,
            "uip_implied_spot": 1.1343,
            "spot_series_key": "eurusd_spot_daily",
            "spot_source_url": "https://data.ecb.europa.eu/data/datasets/EXR/EXR.D.USD.EUR.SP00.A",
            "eur_rate_series_key": "eur_3m_rate",
            "eur_rate_source_url": "https://data.ecb.europa.eu/data/datasets/EST/EST.B.EU000A2QQF32.CR",
            "usd_rate_series_key": "usd_3m_rate",
            "usd_rate_source_url": "https://fred.stlouisfed.org/series/DTB3",
        },
        {
            "pair_key": "eurusd",
            "as_of_date": "2026-05-30",
            "tenor": "6M",
            "spot": 1.14,
            "eur_rate": 2.1,
            "usd_rate": 4.1,
            "rate_spread": -2.0,
            "cip_implied_forward": 1.1288,
            "uip_implied_move_pct": -1.0,
            "uip_implied_spot": 1.1286,
            "spot_series_key": "eurusd_spot_daily",
            "spot_source_url": "https://data.ecb.europa.eu/data/datasets/EXR/EXR.D.USD.EUR.SP00.A",
            "eur_rate_series_key": "eur_6m_rate",
            "eur_rate_source_url": "https://data.ecb.europa.eu/data/datasets/EST/EST.B.EU000A2QQF40.CR",
            "usd_rate_series_key": "usd_6m_rate",
            "usd_rate_source_url": "https://fred.stlouisfed.org/series/DTB6",
        },
        {
            "pair_key": "eurusd",
            "as_of_date": "2026-05-30",
            "tenor": "12M",
            "spot": 1.14,
            "eur_rate": 2.2,
            "usd_rate": 4.2,
            "rate_spread": -2.0,
            "cip_implied_forward": 1.1181,
            "uip_implied_move_pct": -2.0,
            "uip_implied_spot": 1.1172,
            "spot_series_key": "eurusd_spot_daily",
            "spot_source_url": "https://data.ecb.europa.eu/data/datasets/EXR/EXR.D.USD.EUR.SP00.A",
            "eur_rate_series_key": "eur_12m_rate",
            "eur_rate_source_url": "https://data.ecb.europa.eu/data/datasets/EST/EST.B.EU000A2QQF57.CR",
            "usd_rate_series_key": "usd_12m_rate",
            "usd_rate_source_url": "https://fred.stlouisfed.org/series/DTB1YR",
        },
    ]
    assert outputs["availability_rows"] == [
        {
            "pair_key": "eurusd",
            "section_key": "irp",
            "item_key": "3M",
            "status": "available",
            "detail": "CIP and UIP outputs available.",
            "as_of_date": "2026-05-30",
        },
        {
            "pair_key": "eurusd",
            "section_key": "irp",
            "item_key": "6M",
            "status": "available",
            "detail": "CIP and UIP outputs available.",
            "as_of_date": "2026-05-30",
        },
        {
            "pair_key": "eurusd",
            "section_key": "irp",
            "item_key": "12M",
            "status": "available",
            "detail": "CIP and UIP outputs available.",
            "as_of_date": "2026-05-30",
        },
    ]


def test_build_currency_irp_outputs_omits_tenor_rows_when_required_inputs_are_missing():
    outputs = build_currency_irp_outputs([])

    assert outputs["snapshot_rows"] == []
    assert outputs["availability_rows"] == [
        {
            "pair_key": "eurusd",
            "section_key": "irp",
            "item_key": "3M",
            "status": "unavailable",
            "detail": "Required spot or tenor rate inputs are unavailable.",
            "as_of_date": None,
        },
        {
            "pair_key": "eurusd",
            "section_key": "irp",
            "item_key": "6M",
            "status": "unavailable",
            "detail": "Required spot or tenor rate inputs are unavailable.",
            "as_of_date": None,
        },
        {
            "pair_key": "eurusd",
            "section_key": "irp",
            "item_key": "12M",
            "status": "unavailable",
            "detail": "Required spot or tenor rate inputs are unavailable.",
            "as_of_date": None,
        },
    ]
