from src.lib.pipeline.transforms.reference_metrics import build_macro_reference_metrics


def test_build_macro_reference_metrics_creates_us_and_eu_rows_with_dates():
    staging_rows = [
        {
            "series_id": "us_policy_rate",
            "observation_date": "2026-04-01",
            "numeric_value": 4.5,
            "category": "policy_rate",
            "region": "US",
            "frequency": "daily",
            "unit": "percent",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "us_cpi_headline",
            "observation_date": "2025-04-01",
            "numeric_value": 100.0,
            "category": "inflation",
            "region": "US",
            "frequency": "monthly",
            "unit": "index",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "us_cpi_headline",
            "observation_date": "2026-04-01",
            "numeric_value": 103.0,
            "category": "inflation",
            "region": "US",
            "frequency": "monthly",
            "unit": "index",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "us_cpi_core",
            "observation_date": "2025-04-01",
            "numeric_value": 200.0,
            "category": "inflation",
            "region": "US",
            "frequency": "monthly",
            "unit": "index",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "us_cpi_core",
            "observation_date": "2026-04-01",
            "numeric_value": 206.0,
            "category": "inflation",
            "region": "US",
            "frequency": "monthly",
            "unit": "index",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "us_market_real_rate",
            "observation_date": "2026-04-01",
            "numeric_value": 2.1,
            "category": "market_rate",
            "region": "US",
            "frequency": "daily",
            "unit": "percent",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "us_real_gdp",
            "observation_date": "2025-01-01",
            "numeric_value": 100.0,
            "category": "growth",
            "region": "US",
            "frequency": "quarterly",
            "unit": "level",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "us_real_gdp",
            "observation_date": "2025-04-01",
            "numeric_value": 101.0,
            "category": "growth",
            "region": "US",
            "frequency": "quarterly",
            "unit": "level",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "us_real_gdp",
            "observation_date": "2025-07-01",
            "numeric_value": 102.01,
            "category": "growth",
            "region": "US",
            "frequency": "quarterly",
            "unit": "level",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "us_real_gdp",
            "observation_date": "2025-10-01",
            "numeric_value": 103.03,
            "category": "growth",
            "region": "US",
            "frequency": "quarterly",
            "unit": "level",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "us_real_gdp",
            "observation_date": "2026-01-01",
            "numeric_value": 104.06,
            "category": "growth",
            "region": "US",
            "frequency": "quarterly",
            "unit": "level",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "eu_policy_rate",
            "observation_date": "2026-04-01",
            "numeric_value": 2.25,
            "category": "policy_rate",
            "region": "EU",
            "frequency": "daily",
            "unit": "percent",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "eu_hicp_headline",
            "observation_date": "2025-04-01",
            "numeric_value": 100.0,
            "category": "inflation",
            "region": "EU",
            "frequency": "monthly",
            "unit": "index",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "eu_hicp_headline",
            "observation_date": "2026-04-01",
            "numeric_value": 102.1,
            "category": "inflation",
            "region": "EU",
            "frequency": "monthly",
            "unit": "index",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "eu_hicp_core",
            "observation_date": "2025-04-01",
            "numeric_value": 100.0,
            "category": "inflation",
            "region": "EU",
            "frequency": "monthly",
            "unit": "index",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "eu_hicp_core",
            "observation_date": "2026-04-01",
            "numeric_value": 102.3,
            "category": "inflation",
            "region": "EU",
            "frequency": "monthly",
            "unit": "index",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "eu_market_real_rate",
            "observation_date": "2026-04-01",
            "numeric_value": 2.56,
            "category": "market_rate",
            "region": "EU",
            "frequency": "monthly",
            "unit": "percent",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "eu_real_gdp",
            "observation_date": "2025-01-01",
            "numeric_value": 100.0,
            "category": "growth",
            "region": "EU",
            "frequency": "quarterly",
            "unit": "level",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "eu_real_gdp",
            "observation_date": "2025-04-01",
            "numeric_value": 101.0,
            "category": "growth",
            "region": "EU",
            "frequency": "quarterly",
            "unit": "level",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "eu_real_gdp",
            "observation_date": "2025-07-01",
            "numeric_value": 102.01,
            "category": "growth",
            "region": "EU",
            "frequency": "quarterly",
            "unit": "level",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "eu_real_gdp",
            "observation_date": "2025-10-01",
            "numeric_value": 103.03,
            "category": "growth",
            "region": "EU",
            "frequency": "quarterly",
            "unit": "level",
            "provider": "fred",
            "is_valid": True,
        },
        {
            "series_id": "eu_real_gdp",
            "observation_date": "2026-01-01",
            "numeric_value": 104.06,
            "category": "growth",
            "region": "EU",
            "frequency": "quarterly",
            "unit": "level",
            "provider": "ecb",
            "is_valid": True,
        },
    ]

    rows = build_macro_reference_metrics(staging_rows)

    assert rows == [
        {
            "region": "EU",
            "headline_inflation": 2.1,
            "headline_inflation_as_of_date": "2026-04-01",
            "core_inflation": 2.3,
            "core_inflation_as_of_date": "2026-04-01",
            "policy_real_rate": 0.15,
            "policy_real_rate_as_of_date": "2026-04-01",
            "market_real_rate": 0.46,
            "market_real_rate_as_of_date": "2026-04-01",
            "gdp_growth_yoy_current": 4.06,
            "gdp_growth_yoy_historical_average": 4.06,
            "gdp_growth_yoy_gap": 0.0,
            "gdp_growth_yoy_as_of_date": "2026-01-01",
            "gdp_growth_yoy_history_window": "2026-01-01",
            "gdp_growth_qoq_annualized_current": 4.06,
            "gdp_growth_qoq_annualized_historical_average": 4.06,
            "gdp_growth_qoq_annualized_gap": 0.0,
            "gdp_growth_qoq_annualized_as_of_date": "2026-01-01",
            "gdp_growth_qoq_annualized_history_window": "2025-04-01 to 2026-01-01",
            "headline_series_key": "eu_hicp_headline",
            "headline_source_url": "https://fred.stlouisfed.org/series/CP00MI15EA20M086NEST",
            "core_series_key": "eu_hicp_core",
            "core_source_url": "https://fred.stlouisfed.org/series/CPHPLA01EZM661N",
            "market_real_rate_series_key": "eu_market_real_rate",
            "market_real_rate_source_url": "https://fred.stlouisfed.org/series/IRLTLT01EZM156N",
            "gdp_series_key": "eu_real_gdp",
            "gdp_source_url": "https://fred.stlouisfed.org/series/CLV10MNACB1GQSCAEA20Q",
            "policy_real_rate_note": "Policy real rate = policy rate minus headline inflation.",
        },
        {
            "region": "US",
            "headline_inflation": 3.0,
            "headline_inflation_as_of_date": "2026-04-01",
            "core_inflation": 3.0,
            "core_inflation_as_of_date": "2026-04-01",
            "policy_real_rate": 1.5,
            "policy_real_rate_as_of_date": "2026-04-01",
            "market_real_rate": 2.1,
            "market_real_rate_as_of_date": "2026-04-01",
            "gdp_growth_yoy_current": 4.06,
            "gdp_growth_yoy_historical_average": 4.06,
            "gdp_growth_yoy_gap": 0.0,
            "gdp_growth_yoy_as_of_date": "2026-01-01",
            "gdp_growth_yoy_history_window": "2026-01-01",
            "gdp_growth_qoq_annualized_current": 4.06,
            "gdp_growth_qoq_annualized_historical_average": 4.06,
            "gdp_growth_qoq_annualized_gap": 0.0,
            "gdp_growth_qoq_annualized_as_of_date": "2026-01-01",
            "gdp_growth_qoq_annualized_history_window": "2025-04-01 to 2026-01-01",
            "headline_series_key": "us_cpi_headline",
            "headline_source_url": "https://fred.stlouisfed.org/series/CPIAUCSL",
            "core_series_key": "us_cpi_core",
            "core_source_url": "https://fred.stlouisfed.org/series/CPILFESL",
            "market_real_rate_series_key": "us_market_real_rate",
            "market_real_rate_source_url": "https://fred.stlouisfed.org/series/DFII10",
            "gdp_series_key": "us_real_gdp",
            "gdp_source_url": "https://fred.stlouisfed.org/series/GDPC1",
            "policy_real_rate_note": "Policy real rate = policy rate minus headline inflation.",
        },
    ]
