from __future__ import annotations


def replace_macro_reference_metrics(connection, rows: list[dict[str, object]]) -> None:
    with connection.cursor() as cursor:
        if rows:
            cursor.execute(
                "delete from mart.macro_reference_metrics where region = any(%(regions)s)",
                {"regions": sorted({row["region"] for row in rows})},
            )
        cursor.executemany(
            """
            insert into mart.macro_reference_metrics (
                region,
                headline_inflation,
                headline_inflation_as_of_date,
                core_inflation,
                core_inflation_as_of_date,
                policy_real_rate,
                policy_real_rate_as_of_date,
                market_real_rate,
                market_real_rate_as_of_date,
                output_gap,
                output_gap_as_of_date,
                gdp_growth_yoy_current,
                gdp_growth_yoy_historical_average,
                gdp_growth_yoy_gap,
                gdp_growth_yoy_as_of_date,
                gdp_growth_yoy_history_window,
                gdp_growth_qoq_annualized_current,
                gdp_growth_qoq_annualized_historical_average,
                gdp_growth_qoq_annualized_gap,
                gdp_growth_qoq_annualized_as_of_date,
                gdp_growth_qoq_annualized_history_window,
                headline_series_key,
                headline_source_url,
                core_series_key,
                core_source_url,
                market_real_rate_series_key,
                market_real_rate_source_url,
                output_gap_series_key,
                output_gap_source_url,
                gdp_series_key,
                gdp_source_url,
                policy_real_rate_note
            )
            values (
                %(region)s,
                %(headline_inflation)s,
                %(headline_inflation_as_of_date)s,
                %(core_inflation)s,
                %(core_inflation_as_of_date)s,
                %(policy_real_rate)s,
                %(policy_real_rate_as_of_date)s,
                %(market_real_rate)s,
                %(market_real_rate_as_of_date)s,
                %(output_gap)s,
                %(output_gap_as_of_date)s,
                %(gdp_growth_yoy_current)s,
                %(gdp_growth_yoy_historical_average)s,
                %(gdp_growth_yoy_gap)s,
                %(gdp_growth_yoy_as_of_date)s,
                %(gdp_growth_yoy_history_window)s,
                %(gdp_growth_qoq_annualized_current)s,
                %(gdp_growth_qoq_annualized_historical_average)s,
                %(gdp_growth_qoq_annualized_gap)s,
                %(gdp_growth_qoq_annualized_as_of_date)s,
                %(gdp_growth_qoq_annualized_history_window)s,
                %(headline_series_key)s,
                %(headline_source_url)s,
                %(core_series_key)s,
                %(core_source_url)s,
                %(market_real_rate_series_key)s,
                %(market_real_rate_source_url)s,
                %(output_gap_series_key)s,
                %(output_gap_source_url)s,
                %(gdp_series_key)s,
                %(gdp_source_url)s,
                %(policy_real_rate_note)s
            )
            on conflict (region) do update
            set
                headline_inflation = excluded.headline_inflation,
                headline_inflation_as_of_date = excluded.headline_inflation_as_of_date,
                core_inflation = excluded.core_inflation,
                core_inflation_as_of_date = excluded.core_inflation_as_of_date,
                policy_real_rate = excluded.policy_real_rate,
                policy_real_rate_as_of_date = excluded.policy_real_rate_as_of_date,
                market_real_rate = excluded.market_real_rate,
                market_real_rate_as_of_date = excluded.market_real_rate_as_of_date,
                output_gap = excluded.output_gap,
                output_gap_as_of_date = excluded.output_gap_as_of_date,
                gdp_growth_yoy_current = excluded.gdp_growth_yoy_current,
                gdp_growth_yoy_historical_average = excluded.gdp_growth_yoy_historical_average,
                gdp_growth_yoy_gap = excluded.gdp_growth_yoy_gap,
                gdp_growth_yoy_as_of_date = excluded.gdp_growth_yoy_as_of_date,
                gdp_growth_yoy_history_window = excluded.gdp_growth_yoy_history_window,
                gdp_growth_qoq_annualized_current = excluded.gdp_growth_qoq_annualized_current,
                gdp_growth_qoq_annualized_historical_average = excluded.gdp_growth_qoq_annualized_historical_average,
                gdp_growth_qoq_annualized_gap = excluded.gdp_growth_qoq_annualized_gap,
                gdp_growth_qoq_annualized_as_of_date = excluded.gdp_growth_qoq_annualized_as_of_date,
                gdp_growth_qoq_annualized_history_window = excluded.gdp_growth_qoq_annualized_history_window,
                headline_series_key = excluded.headline_series_key,
                headline_source_url = excluded.headline_source_url,
                core_series_key = excluded.core_series_key,
                core_source_url = excluded.core_source_url,
                market_real_rate_series_key = excluded.market_real_rate_series_key,
                market_real_rate_source_url = excluded.market_real_rate_source_url,
                output_gap_series_key = excluded.output_gap_series_key,
                output_gap_source_url = excluded.output_gap_source_url,
                gdp_series_key = excluded.gdp_series_key,
                gdp_source_url = excluded.gdp_source_url,
                policy_real_rate_note = excluded.policy_real_rate_note
            """,
            rows,
        )
    connection.commit()
